apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-id-center
  name: go-id-center
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-id-center
  strategy: { }
  template:
    metadata:
      annotations:
        prometheus.io/port: "19002"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/monitor/prometheus"
      labels:
        app: go-id-center
    spec:
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/star_main/go-id-center:${TIMESTAMP}
          name: go-id-center
          resources:
            limits:
              memory: "512Mi"
          imagePullPolicy: Always
          env:
            - name: profile
              value: ${PROFILE}
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      # 应用部署所在节点选择 arm64 或 amd64
      nodeSelector:
        kubernetes.io/arch: arm64
status: { }
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-id-center
  name: go-id-center-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: monitor
      port: 19002
      protocol: TCP
      targetPort: 19002
  selector:
    app: go-id-center
  type: ClusterIP
status:
  loadBalancer: { }
